# ============================================
# Datasource Elasticsearch auto-configurée
# Les apprenants n'ont rien à faire !
# ============================================

apiVersion: 1

datasources:
  - name: Elasticsearch - Anime
    uid: elasticsearch-anime
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "anime_final"
    isDefault: true
    editable: true
    jsonData:
      index: "anime_final"
      esVersion: "8.12.0"
      timeField: "indexed_at"
      logLevelField: ""
      logMessageField: ""
      maxConcurrentShardRequests: 5
